//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "tracker_pings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub number_plate: String,
    #[sea_orm(column_type = "Double")]
    pub latitude: f64,
    #[sea_orm(column_type = "Double")]
    pub longitude: f64,
    #[sea_orm(column_type = "Double")]
    pub speed: f64,
    pub recorded_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::vehicles::Entity",
        from = "Column::NumberPlate",
        to = "super::vehicles::Column::NumberPlate",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Vehicles,
}

impl Related<super::vehicles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Vehicles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
