//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "vehicles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub number_plate: String,
    pub make: String,
    pub model: String,
    pub year: i32,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tracker_pings::Entity")]
    TrackerPings,
}

impl Related<super::tracker_pings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TrackerPings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
